name: "Send ClickUp Notification Action"

description: "Fetches commit history (if possible) and sends a notification to ClickUp."

branding:
  icon: "bell"
  color: "orange"

inputs:
  clickup_api_token:
    description: "ClickUp API Token"
    required: true
  clickup_workspace_id:
    description: "ClickUp Workspace ID"
    required: true
  clickup_channel_id:
    description: "ClickUp Channel ID"
    required: true
  clickup_project_name:
    description: "ClickUp Project Name for the message"
    required: true
  show_fetch_duration:
    description: "Show duration information in the notification"
    required: false
    default: "true"
  show_changelog_commits:
    description: "Show changelog commits in the notification"
    required: false
    default: "true"
  full_commit_message:
    description: "Use the full commit message instead of the first line"
    required: false
    default: "true"
  title:
    description: "Custom title for the notification message"
    required: false
    default: ""
  description:
    description: "Custom description for the notification message"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "CLICKUP_WORKSPACE_ID=${{ inputs.clickup_workspace_id }}" >> $GITHUB_ENV
        echo "CLICKUP_PROJECT_NAME=${{ inputs.clickup_project_name }}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ github.token }}" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "TRIGGERING_ACTOR=$GITHUB_ACTOR" >> $GITHUB_ENV

    - name: ⏱️ Fetch Duration
      id: duration
      if: ${{ inputs.show_fetch_duration == 'true' }}
      uses: architweb/ClickUpNotification/steps/fetch-duration@v2.0.1

    - name: 📝 Fetch Commits
      id: commits
      if: ${{ inputs.show_changelog_commits == 'true' }}
      uses: architweb/ClickUpNotification/steps/fetch-commits@v2.0.1
      with:
        full_commit_message: ${{ inputs.full_commit_message }}

    - name: 📢 Send ClickUp Notification
      uses: architweb/ClickUpNotification/steps/send-notification@v2.0.1
      with:
        clickup_api_token: ${{ inputs.clickup_api_token }}
        clickup_workspace_id: ${{ inputs.clickup_workspace_id }}
        clickup_channel_id: ${{ inputs.clickup_channel_id }}
        clickup_project_name: ${{ inputs.clickup_project_name }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        formatted_duration: ${{ inputs.show_fetch_duration == 'true' && steps.duration.outputs.formatted_duration || 'unknown' }}
        commit_file: ${{ inputs.show_changelog_commits == 'true' && steps.commits.outputs.commit_file || '' }}
