name: "⏱️ Fetch Duration"
description: "Fetches the workflow execution duration"

outputs:
  formatted_duration:
    description: "Formatted duration in MM:SS format"
    value: ${{ steps.duration.outputs.FORMATTED_DURATION }}

runs:
  using: "composite"
  steps:
    - name: Calculate Duration
      id: duration
      shell: bash
      run: |
        STARTED_AT=""
        FORMATTED_DURATION="unknown"

        if command -v gh &> /dev/null; then
          STARTED_AT=$(gh api "repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" --jq '.run_started_at' 2>/dev/null || echo "")

          if [ -n "$STARTED_AT" ]; then
            COMPLETED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            if command -v date &> /dev/null; then
              START_EPOCH=$(date -d "$STARTED_AT" +%s 2>/dev/null || echo "")
              END_EPOCH=$(date -d "$COMPLETED_AT" +%s 2>/dev/null || echo "")

              if [ -n "$START_EPOCH" ] && [ -n "$END_EPOCH" ]; then
                DURATION=$((END_EPOCH - START_EPOCH))
                FORMATTED_DURATION=$(printf "%02d:%02d" $((DURATION / 60)) $((DURATION % 60)))
              fi
            fi
          fi
        fi

        echo "FORMATTED_DURATION=${FORMATTED_DURATION}" >> $GITHUB_OUTPUT
